task :default do 
	ARGV.each { |a| task a.to_sym do ; end } 
	if ARGV[1].nil?
		puts "Sorry, command not understood. Please use: \n$ rake -T\nto see a list of all available rake tasks."
	end
end

desc 'Patches Liferay Journal Articles'
task :patch do
	ruby 'script.rb'
	puts 'Success!'
end